services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  embed:  # embed + upsert
    build:
      context: ./02_embedding
      dockerfile: Dockerfile
    environment:
      QDRANT_URL: "http://localhost:6333"
      QDRANT_COLLECTION: "mental_health_vi"
      QDRANT_DISTANCE: "cosine"
    volumes:
      - ..:/workspace
    working_dir: /workspace
    depends_on:
      - qdrant
    command: >
      python src/02_embedding/03_embedding.py

volumes:
  qdrant_storage:
