services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  retrieval:
    image: khanhle04/retrieval:latest
    environment:
      QDRANT_URL: "http://qdrant:6333"
      QDRANT_COLLECTION: "mental_health_vi"
      EMBED_MODEL: "AITeamVN/Vietnamese_Embedding_v2"
    ports:
      - "5000:5000"
    depends_on:
      - qdrant

  # FastAPI Embedding Service
  deploy-embedding:
    build:
      context: ./deploy_embedding
      dockerfile: Dockerfile
    # image: khanhle04/deploy-embedding:latest  # Use this if image is pre-built
    environment:
      PORT: "8000"
      PYTHONUNBUFFERED: "1"
      HF_HOME: "/app/.cache/huggingface"
    ports:
      - "8000:8000"
    volumes:
      - model_cache:/app/.cache/huggingface  # Shared model cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: "2.0"
        reservations:
          memory: 1G
          cpus: "1.0"

volumes:
  qdrant_storage:
  model_cache:  # Shared cache for models
