# Docker Compose override for embedding service only
# Usage: docker-compose -f docker-compose.yml -f docker-compose.embedding.yml up deploy-embedding

services:
  # FastAPI Embedding Service (standalone)
  deploy-embedding:
    build:
      context: ./deploy_embedding
      dockerfile: Dockerfile
    environment:
      PORT: "5000"
      PYTHONUNBUFFERED: "1"
      HF_HOME: "/app/.cache/huggingface"
      # Optional: Change model if needed
      # MODEL_NAME: "sentence-transformers/all-MiniLM-L6-v2"
    ports:
      - "5000:5000"
    volumes:
      - model_cache:/app/.cache/huggingface
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: "2.0"
        reservations:
          memory: 1G
          cpus: "1.0"

volumes:
  model_cache:
    driver: local
