services:
  upsert:
    build:
      context: ./02_embedding
      dockerfile: Dockerfile
    environment:
      QDRANT_URL: "http://localhost:6333"
      # QDRANT_API_KEY: ""
    volumes:
      - ..:/workspace
    working_dir: /workspace
    command: >
      python src/02_embedding/03b_upsert_qdrant.py
      --emb_dir data/embeddings
      --chunks_dir data/processed/chunks
      --qdrant_url http://localhost:6333
      --collection mental_health_vi
      --distance cosine